### ISSUE TITLE
Bugs that i found so far 

### ISSUE THREAD

**Issue by BlackDragon126** [zwya/Weapon-Mastery#1]
is my first time posting log so idk if i link the right one's 
Btw Nice work for your first mod 

 -Bugs- 
 1. Can't make a new save. Here the logs (https://gist.github.com/7b084a5f44468809245356e66a156c2f)
 2. Can't generate new pawns.  Like raiders  (https://gist.github.com/e4a7322c99dbffc0caacea7c2f48e0c7)
 3. Can't spawn items using DEV or character editor 

-I tried with and without using  Rocketman.  Perfomance optimizer  and RuntimeGC  same problem 
-mod need to be after "hugs" and after aliens race to work (can make new save but can't spawn pawns)
-by removing the mod the game works fine  else work's fine

**Comment by AhHanie** [comment]
I updated the mod. Let me know if the issues are resolved.

**Comment by BlackDragon126** [comment]
@zwya nope 
now i have only weapon mastery active and still the same problem 
-logs-
https://gist.github.com/f7c72d01a8fd7510351da06d5ddf4869
IM STUPID Forgot to update it xD

**Comment by AhHanie** [comment]
It happens to the best of us :)
